### ISSUE TITLE
New Post Small

### ISSUE THREAD

**Issue by MECU** [FbF/Laravel-Blog#11]
I'm using the Frozennode Admistrator with the posts module provided. Clicking to make a new post has the new post entry about 20% of the screen width, and the listing of posts the other 80%. I would expect it to be the opposite or the listing of posts omitted.

![image](https://f.cloud.github.com/assets/4950394/2232401/67532b06-9b1b-11e3-8e28-b1d7ffb4b2bd.png)

**Comment by neilcrookes** [comment]
This is the behaviour of the administrator package, although you can control the width of the new/edit panels in the administrator config, check out the docs, it's something 'form_width' => 500, this is pixels.
