### ISSUE TITLE
Configuration not found

### ISSUE THREAD

**Issue by ghost** [FbF/Laravel-Blog#13]
Hey,

i`m totally new to lavarel and i tried to install your blog.
But i get some errors with artisan

![image](https://cloud.githubusercontent.com/assets/2776503/2576821/05609644-b976-11e3-82a9-59ed86991865.png)

And in the Frontend i get this error:

Illuminate \ Database \ QueryException
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'lavarel.fbf_blog_posts' doesn't exist (SQL: select count(*) as aggregate from `fbf_blog_posts` where `fbf_blog_posts`.`status` = APPROVED and `fbf_blog_posts`.`published_date` <= 2014-04-01 08:19:25)

What do i wrong ?

**Comment by neilcrookes** [comment]
Hi,

Have you definitely installed the package through composer? And have you installed it into the project at c:\wamp\www\laravel ?

After running

$ composer update

all the composer autoload files should be regenerated and the package's files should be found. Can you search for "LaravelBlog" inside the vendor/composer directory to make sure it's been picked up?

If it's not there, make sure that you have the package files in the vendor/fbf/laravel-blog directory, and then run:

$ php artisan dump-autoload

Good luck.

Neil

**Comment by ghost** [comment]
How can i find out if it were installed to c:\wamp\www\laravel ?

I made a screenshot how i did it

![image](https://cloud.githubusercontent.com/assets/2776503/2577498/7b9a8c8e-b980-11e3-8021-fd5b5d6ff312.png)

This is my compser file in C:/users/chris

![image](https://cloud.githubusercontent.com/assets/2776503/2577721/28374f8e-b983-11e3-9ab9-67a23f0b2eba.png)

**Comment by neilcrookes** [comment]
The composer.json file that you add the packages to, should be the one in the folder where you are running composer update. I.e. the one in the folder at c:\wamp\www\laravel. Not the one in c:\users\chris

**Comment by ghost** [comment]
Ahh okay now the composer is working :+1: 

But now i`m getting this error:

![image](https://cloud.githubusercontent.com/assets/2776503/2577926/614db4ae-b986-11e3-8da9-5677f04878fd.png)

**Comment by neilcrookes** [comment]
Have you followed all the steps in the installation section in the readme? Have you done anything different to what was mentioned there?

**Comment by ghost** [comment]
Yea maybe the problem is this isn a complete new installation.

i already created some views and started developing my site with really simple views.

i chaged the routes.php to your routes.php and changed my view file "default.blade.php" to "master.blade.php" in "app/views/layouts".

But i`ve also already some header,footer views "app/views/includes".

**Comment by neilcrookes** [comment]
This isn't an issue with the package. Sorry dude, but I don't have time to help you debug you particular application. Good luck sorting out your app.

**Comment by ghost** [comment]
ok anyway thanks for your help and time ;)
