### ISSUE TITLE
Mark this with releases 

### ISSUE THREAD

**Issue by johnnye** [FbF/Laravel-Blog#2]
Hi, 
Would it be possible to mark this with a release? It makes it easer to use in production as we can fix it to a release rather then constantly using dev-master which isn't best practice. 

I'd suggest starting at 0.1.0 for this release. 

Thanks.

**Comment by neilcrookes** [comment]
Your wish is my command ;-)

**Comment by johnnye** [comment]
Thanks, much appreciated.
