### ISSUE TITLE
Can't seem to change the way the date is displayed on posts, meta descriptions, etc.

### ISSUE THREAD

**Issue by singhjay** [FbF/Laravel-Blog#26]
For example, in my vendor/fbf/laravel-blog/src/config/views.php, I have:

```
<?php

/**
 * Configuration options for the built-in views
 */
return array(

    /**
     * Date format for published date, shown on partials.list and partials.details. Should be
     * a valid date() format string, e.g.
     *
     * @type string
     */
    'published_date_format' => 'jS F, Y',
```

, but yet the blog doesn't seem to be reading and updating. Same thing goes with the header tag, it still reads "My Blog" instead of what I actually set it to.

**Comment by neilcrookes** [comment]
You should never amend the files in vendor. The `php artisan config:publish` command copies the config from the vendor directory to your `app/config/packages` directory. Update the settings in this config file.
