### ISSUE TITLE
Messages configuration

### ISSUE THREAD

**Issue by legendarydrew** [FbF/Laravel-Blog#39]
First of all, thanks very much for this packagae - it has saved a lot of time, even though I've done a little modification for my own requirements.

Speaking of which, I've noticed that there isn't a configuration file for the messages that get used in the views, for example:

`{{ trans('laravel-blog::messages.share.facebook') }}`

After publishing the configration to my project, I've tried creating a configuration file called messages.php under the package's config directory, with the following contents:

```
return array(
    'adjacent' => array (
        'prev_link_text' => '&lt; :title',
        'next_link_text' => '&gt; :title'
    ),
    'share' => array (
        'twitter' => 'Yo!'
    )
);
```

However this doesn't change the output at all. Have I done something wrong?

**Comment by neilcrookes** [comment]
Check out how to override package translation files here:

http://laravel.com/docs/4.2/localization#overriding-package-language-files

They don't go in the config directory

**Comment by legendarydrew** [comment]
Ah, it's a language file. (trans() should have given me a clue!)

Thanks very much for the quick response!
