### ISSUE TITLE
"Year"

### ISSUE THREAD

**Issue by johnnye** [FbF/Laravel-Blog#7]
Year not a known function in SQLite, this won't work with projects that rely on SQLite either for testing or in production.

**Comment by neilcrookes** [comment]
I have made the PostsController accept an instance of a custom model that extends the package's Post model, and moved the function to filter by year/month, so you can override the scopeByYearMonth() and archives() methods in your model for SQLite, or any other engine. See version 0.4.0.

**Comment by greeven** [comment]
What is the best way to implement that using SQLite for development on local and MySQL for production online?

A code snippet would be awesome here!
